// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _MAJ_HH_
#define _MAJ_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct MAJ : public sc_module {
    // Port declarations 6
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x;
    sc_in< sc_lv<32> > y;
    sc_in< sc_lv<32> > z;
    sc_in< sc_lv<32> > rtl_key_r;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    MAJ(sc_module_name name);
    SC_HAS_PROCESS(MAJ);

    ~MAJ();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<32> > xor_ln136_fu_46_p2;
    sc_signal< sc_lv<32> > and_ln136_fu_52_p2;
    sc_signal< sc_lv<32> > and_ln136_1_fu_58_p2;
    sc_signal< sc_lv<32> > and_ln142_fu_70_p2;
    sc_signal< sc_lv<32> > or_ln142_fu_76_p2;
    sc_signal< sc_lv<32> > or_ln142_1_fu_82_p2;
    sc_signal< sc_lv<32> > xor_ln142_fu_88_p2;
    sc_signal< sc_lv<32> > xor_ln142_1_fu_94_p2;
    sc_signal< sc_lv<1> > tmp_fu_38_p3;
    sc_signal< sc_lv<32> > xor_ln142_2_fu_100_p2;
    sc_signal< sc_lv<32> > xor_ln136_1_fu_64_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_and_ln136_1_fu_58_p2();
    void thread_and_ln136_fu_52_p2();
    void thread_and_ln142_fu_70_p2();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_or_ln142_1_fu_82_p2();
    void thread_or_ln142_fu_76_p2();
    void thread_tmp_fu_38_p3();
    void thread_xor_ln136_1_fu_64_p2();
    void thread_xor_ln136_fu_46_p2();
    void thread_xor_ln142_1_fu_94_p2();
    void thread_xor_ln142_2_fu_100_p2();
    void thread_xor_ln142_fu_88_p2();
};

}

using namespace ap_rtl;

#endif
