-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MAJ is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    y : IN STD_LOGIC_VECTOR (31 downto 0);
    z : IN STD_LOGIC_VECTOR (31 downto 0);
    rtl_key_r : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of MAJ is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal xor_ln133_fu_46_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln133_fu_52_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln133_1_fu_58_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln139_fu_70_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln139_fu_76_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln139_1_fu_82_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln139_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln139_1_fu_94_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_38_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln139_2_fu_100_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln133_1_fu_64_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    and_ln133_1_fu_58_p2 <= (z and y);
    and_ln133_fu_52_p2 <= (xor_ln133_fu_46_p2 and x);
    and_ln139_fu_70_p2 <= (y and x);
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        xor_ln139_2_fu_100_p2 when (tmp_fu_38_p3(0) = '1') else 
        xor_ln133_1_fu_64_p2;
    or_ln139_1_fu_82_p2 <= (z or y);
    or_ln139_fu_76_p2 <= (z or x);
    tmp_fu_38_p3 <= rtl_key_r(4 downto 4);
    xor_ln133_1_fu_64_p2 <= (and_ln133_fu_52_p2 xor and_ln133_1_fu_58_p2);
    xor_ln133_fu_46_p2 <= (z xor y);
    xor_ln139_1_fu_94_p2 <= (or_ln139_1_fu_82_p2 xor ap_const_lv32_FFFFFFFF);
    xor_ln139_2_fu_100_p2 <= (xor_ln139_fu_88_p2 xor xor_ln139_1_fu_94_p2);
    xor_ln139_fu_88_p2 <= (or_ln139_fu_76_p2 xor and_ln139_fu_70_p2);
end behav;
