// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _SIG1_HH_
#define _SIG1_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct SIG1 : public sc_module {
    // Port declarations 4
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x;
    sc_in< sc_lv<32> > rtl_key_r;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    SIG1(sc_module_name name);
    SC_HAS_PROCESS(SIG1);

    ~SIG1();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<32> > xor_ln231_1_fu_223_p2;
    sc_signal< sc_lv<32> > ap_phi_mux_p_0_phi_fu_77_p4;
    sc_signal< sc_lv<1> > temp_fu_87_p1;
    sc_signal< sc_lv<32> > xor_ln235_1_fu_354_p2;
    sc_signal< sc_lv<25> > trunc_ln56_2_fu_99_p1;
    sc_signal< sc_lv<7> > lshr_ln56_2_fu_103_p4;
    sc_signal< sc_lv<7> > trunc_ln60_2_fu_131_p1;
    sc_signal< sc_lv<25> > lshr_ln60_2_fu_121_p4;
    sc_signal< sc_lv<1> > tmp_fu_91_p3;
    sc_signal< sc_lv<32> > or_ln60_2_fu_135_p3;
    sc_signal< sc_lv<32> > or_ln56_2_fu_113_p3;
    sc_signal< sc_lv<14> > trunc_ln56_3_fu_151_p1;
    sc_signal< sc_lv<18> > lshr_ln56_3_fu_155_p4;
    sc_signal< sc_lv<18> > trunc_ln60_3_fu_183_p1;
    sc_signal< sc_lv<14> > lshr_ln60_3_fu_173_p4;
    sc_signal< sc_lv<32> > or_ln60_3_fu_187_p3;
    sc_signal< sc_lv<32> > or_ln56_3_fu_165_p3;
    sc_signal< sc_lv<29> > lshr_ln6_fu_203_p4;
    sc_signal< sc_lv<32> > zext_ln231_fu_213_p1;
    sc_signal< sc_lv<32> > select_ln54_3_fu_195_p3;
    sc_signal< sc_lv<32> > xor_ln231_fu_217_p2;
    sc_signal< sc_lv<32> > select_ln54_2_fu_143_p3;
    sc_signal< sc_lv<15> > trunc_ln56_fu_230_p1;
    sc_signal< sc_lv<17> > lshr_ln_fu_234_p4;
    sc_signal< sc_lv<17> > trunc_ln60_fu_262_p1;
    sc_signal< sc_lv<15> > lshr_ln4_fu_252_p4;
    sc_signal< sc_lv<32> > or_ln1_fu_266_p3;
    sc_signal< sc_lv<32> > or_ln_fu_244_p3;
    sc_signal< sc_lv<13> > trunc_ln56_1_fu_282_p1;
    sc_signal< sc_lv<19> > lshr_ln56_1_fu_286_p4;
    sc_signal< sc_lv<19> > trunc_ln60_1_fu_314_p1;
    sc_signal< sc_lv<13> > lshr_ln60_1_fu_304_p4;
    sc_signal< sc_lv<32> > or_ln60_1_fu_318_p3;
    sc_signal< sc_lv<32> > or_ln56_1_fu_296_p3;
    sc_signal< sc_lv<22> > lshr_ln5_fu_334_p4;
    sc_signal< sc_lv<32> > zext_ln235_fu_344_p1;
    sc_signal< sc_lv<32> > select_ln54_1_fu_326_p3;
    sc_signal< sc_lv<32> > xor_ln235_fu_348_p2;
    sc_signal< sc_lv<32> > select_ln54_fu_274_p3;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_phi_mux_p_0_phi_fu_77_p4();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_lshr_ln4_fu_252_p4();
    void thread_lshr_ln56_1_fu_286_p4();
    void thread_lshr_ln56_2_fu_103_p4();
    void thread_lshr_ln56_3_fu_155_p4();
    void thread_lshr_ln5_fu_334_p4();
    void thread_lshr_ln60_1_fu_304_p4();
    void thread_lshr_ln60_2_fu_121_p4();
    void thread_lshr_ln60_3_fu_173_p4();
    void thread_lshr_ln6_fu_203_p4();
    void thread_lshr_ln_fu_234_p4();
    void thread_or_ln1_fu_266_p3();
    void thread_or_ln56_1_fu_296_p3();
    void thread_or_ln56_2_fu_113_p3();
    void thread_or_ln56_3_fu_165_p3();
    void thread_or_ln60_1_fu_318_p3();
    void thread_or_ln60_2_fu_135_p3();
    void thread_or_ln60_3_fu_187_p3();
    void thread_or_ln_fu_244_p3();
    void thread_select_ln54_1_fu_326_p3();
    void thread_select_ln54_2_fu_143_p3();
    void thread_select_ln54_3_fu_195_p3();
    void thread_select_ln54_fu_274_p3();
    void thread_temp_fu_87_p1();
    void thread_tmp_fu_91_p3();
    void thread_trunc_ln56_1_fu_282_p1();
    void thread_trunc_ln56_2_fu_99_p1();
    void thread_trunc_ln56_3_fu_151_p1();
    void thread_trunc_ln56_fu_230_p1();
    void thread_trunc_ln60_1_fu_314_p1();
    void thread_trunc_ln60_2_fu_131_p1();
    void thread_trunc_ln60_3_fu_183_p1();
    void thread_trunc_ln60_fu_262_p1();
    void thread_xor_ln231_1_fu_223_p2();
    void thread_xor_ln231_fu_217_p2();
    void thread_xor_ln235_1_fu_354_p2();
    void thread_xor_ln235_fu_348_p2();
    void thread_zext_ln231_fu_213_p1();
    void thread_zext_ln235_fu_344_p1();
};

}

using namespace ap_rtl;

#endif
