// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CH (
        ap_ready,
        x,
        y,
        z,
        rtl_key_r,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] y;
input  [31:0] z;
input  [31:0] rtl_key_r;
output  [31:0] ap_return;

wire   [31:0] xor_ln93_fu_46_p2;
wire   [31:0] or_ln93_fu_52_p2;
wire   [31:0] and_ln97_1_fu_70_p2;
wire   [31:0] and_ln97_fu_64_p2;
wire   [0:0] tmp_fu_38_p3;
wire   [31:0] xor_ln97_fu_76_p2;
wire   [31:0] or_ln93_1_fu_58_p2;

assign and_ln97_1_fu_70_p2 = (z & xor_ln93_fu_46_p2);

assign and_ln97_fu_64_p2 = (y & x);

assign ap_ready = 1'b1;

assign ap_return = ((tmp_fu_38_p3[0:0] === 1'b1) ? xor_ln97_fu_76_p2 : or_ln93_1_fu_58_p2);

assign or_ln93_1_fu_58_p2 = (y | or_ln93_fu_52_p2);

assign or_ln93_fu_52_p2 = (z | xor_ln93_fu_46_p2);

assign tmp_fu_38_p3 = rtl_key_r[32'd5];

assign xor_ln93_fu_46_p2 = (x ^ 32'd4294967295);

assign xor_ln97_fu_76_p2 = (and_ln97_fu_64_p2 ^ and_ln97_1_fu_70_p2);

endmodule //CH
