// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module EP0 (
        ap_ready,
        x,
        rtl_key_r,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] rtl_key_r;
output  [31:0] ap_return;

wire   [31:0] xor_ln158_1_fu_269_p2;
reg   [31:0] ap_phi_mux_p_0_phi_fu_81_p4;
wire   [0:0] tmp_fu_91_p3;
wire   [31:0] xor_ln164_fu_380_p2;
wire   [29:0] trunc_ln53_12_fu_107_p1;
wire   [1:0] lshr_ln_fu_111_p4;
wire   [1:0] trunc_ln57_12_fu_139_p1;
wire   [29:0] lshr_ln1_fu_129_p4;
wire   [0:0] tmp_5_fu_99_p3;
wire   [31:0] or_ln4_fu_143_p3;
wire   [31:0] or_ln_fu_121_p3;
wire   [18:0] trunc_ln53_13_fu_159_p1;
wire   [12:0] lshr_ln53_s_fu_163_p4;
wire   [12:0] trunc_ln57_13_fu_191_p1;
wire   [18:0] lshr_ln57_s_fu_181_p4;
wire   [31:0] or_ln57_s_fu_195_p3;
wire   [31:0] or_ln53_s_fu_173_p3;
wire   [9:0] trunc_ln53_14_fu_211_p1;
wire   [21:0] lshr_ln53_1_fu_215_p4;
wire   [21:0] trunc_ln57_14_fu_243_p1;
wire   [9:0] lshr_ln57_1_fu_233_p4;
wire   [31:0] or_ln57_1_fu_247_p3;
wire   [31:0] or_ln53_1_fu_225_p3;
wire   [31:0] select_ln51_fu_151_p3;
wire   [31:0] select_ln51_12_fu_255_p3;
wire   [31:0] xor_ln158_fu_263_p2;
wire   [31:0] select_ln51_11_fu_203_p3;
wire   [25:0] trunc_ln53_fu_276_p1;
wire   [5:0] lshr_ln53_2_fu_280_p4;
wire   [5:0] trunc_ln57_fu_308_p1;
wire   [25:0] lshr_ln57_2_fu_298_p4;
wire   [31:0] or_ln57_2_fu_312_p3;
wire   [31:0] or_ln53_2_fu_290_p3;
wire   [13:0] trunc_ln53_11_fu_328_p1;
wire   [17:0] lshr_ln53_3_fu_332_p4;
wire   [17:0] trunc_ln57_11_fu_360_p1;
wire   [13:0] lshr_ln57_3_fu_350_p4;
wire   [31:0] or_ln57_3_fu_364_p3;
wire   [31:0] or_ln53_3_fu_342_p3;
wire   [31:0] select_ln51_14_fu_372_p3;
wire   [31:0] select_ln51_13_fu_320_p3;

always @ (*) begin
    if ((tmp_fu_91_p3 == 1'd1)) begin
        ap_phi_mux_p_0_phi_fu_81_p4 = xor_ln164_fu_380_p2;
    end else if ((tmp_fu_91_p3 == 1'd0)) begin
        ap_phi_mux_p_0_phi_fu_81_p4 = xor_ln158_1_fu_269_p2;
    end else begin
        ap_phi_mux_p_0_phi_fu_81_p4 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign ap_return = ap_phi_mux_p_0_phi_fu_81_p4;

assign lshr_ln1_fu_129_p4 = {{x[31:2]}};

assign lshr_ln53_1_fu_215_p4 = {{x[31:10]}};

assign lshr_ln53_2_fu_280_p4 = {{x[31:26]}};

assign lshr_ln53_3_fu_332_p4 = {{x[31:14]}};

assign lshr_ln53_s_fu_163_p4 = {{x[31:19]}};

assign lshr_ln57_1_fu_233_p4 = {{x[31:22]}};

assign lshr_ln57_2_fu_298_p4 = {{x[31:6]}};

assign lshr_ln57_3_fu_350_p4 = {{x[31:18]}};

assign lshr_ln57_s_fu_181_p4 = {{x[31:13]}};

assign lshr_ln_fu_111_p4 = {{x[31:30]}};

assign or_ln4_fu_143_p3 = {{trunc_ln57_12_fu_139_p1}, {lshr_ln1_fu_129_p4}};

assign or_ln53_1_fu_225_p3 = {{trunc_ln53_14_fu_211_p1}, {lshr_ln53_1_fu_215_p4}};

assign or_ln53_2_fu_290_p3 = {{trunc_ln53_fu_276_p1}, {lshr_ln53_2_fu_280_p4}};

assign or_ln53_3_fu_342_p3 = {{trunc_ln53_11_fu_328_p1}, {lshr_ln53_3_fu_332_p4}};

assign or_ln53_s_fu_173_p3 = {{trunc_ln53_13_fu_159_p1}, {lshr_ln53_s_fu_163_p4}};

assign or_ln57_1_fu_247_p3 = {{trunc_ln57_14_fu_243_p1}, {lshr_ln57_1_fu_233_p4}};

assign or_ln57_2_fu_312_p3 = {{trunc_ln57_fu_308_p1}, {lshr_ln57_2_fu_298_p4}};

assign or_ln57_3_fu_364_p3 = {{trunc_ln57_11_fu_360_p1}, {lshr_ln57_3_fu_350_p4}};

assign or_ln57_s_fu_195_p3 = {{trunc_ln57_13_fu_191_p1}, {lshr_ln57_s_fu_181_p4}};

assign or_ln_fu_121_p3 = {{trunc_ln53_12_fu_107_p1}, {lshr_ln_fu_111_p4}};

assign select_ln51_11_fu_203_p3 = ((tmp_5_fu_99_p3[0:0] === 1'b1) ? or_ln57_s_fu_195_p3 : or_ln53_s_fu_173_p3);

assign select_ln51_12_fu_255_p3 = ((tmp_5_fu_99_p3[0:0] === 1'b1) ? or_ln57_1_fu_247_p3 : or_ln53_1_fu_225_p3);

assign select_ln51_13_fu_320_p3 = ((tmp_5_fu_99_p3[0:0] === 1'b1) ? or_ln57_2_fu_312_p3 : or_ln53_2_fu_290_p3);

assign select_ln51_14_fu_372_p3 = ((tmp_5_fu_99_p3[0:0] === 1'b1) ? or_ln57_3_fu_364_p3 : or_ln53_3_fu_342_p3);

assign select_ln51_fu_151_p3 = ((tmp_5_fu_99_p3[0:0] === 1'b1) ? or_ln4_fu_143_p3 : or_ln_fu_121_p3);

assign tmp_5_fu_99_p3 = rtl_key_r[32'd6];

assign tmp_fu_91_p3 = rtl_key_r[32'd3];

assign trunc_ln53_11_fu_328_p1 = x[13:0];

assign trunc_ln53_12_fu_107_p1 = x[29:0];

assign trunc_ln53_13_fu_159_p1 = x[18:0];

assign trunc_ln53_14_fu_211_p1 = x[9:0];

assign trunc_ln53_fu_276_p1 = x[25:0];

assign trunc_ln57_11_fu_360_p1 = x[17:0];

assign trunc_ln57_12_fu_139_p1 = x[1:0];

assign trunc_ln57_13_fu_191_p1 = x[12:0];

assign trunc_ln57_14_fu_243_p1 = x[21:0];

assign trunc_ln57_fu_308_p1 = x[5:0];

assign xor_ln158_1_fu_269_p2 = (xor_ln158_fu_263_p2 ^ select_ln51_11_fu_203_p3);

assign xor_ln158_fu_263_p2 = (select_ln51_fu_151_p3 ^ select_ln51_12_fu_255_p3);

assign xor_ln164_fu_380_p2 = (select_ln51_14_fu_372_p3 ^ select_ln51_13_fu_320_p3);

endmodule //EP0
