// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module EP1 (
        ap_ready,
        x,
        rtl_key_r,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] rtl_key_r;
output  [31:0] ap_return;

wire   [31:0] xor_ln181_fu_211_p2;
reg   [31:0] ap_phi_mux_p_0_phi_fu_81_p4;
wire   [0:0] tmp_fu_91_p3;
wire   [31:0] xor_ln186_1_fu_380_p2;
wire   [27:0] trunc_ln53_9_fu_107_p1;
wire   [3:0] lshr_ln_fu_111_p4;
wire   [3:0] trunc_ln57_9_fu_139_p1;
wire   [27:0] lshr_ln9_fu_129_p4;
wire   [0:0] tmp_4_fu_99_p3;
wire   [31:0] or_ln3_fu_143_p3;
wire   [31:0] or_ln_fu_121_p3;
wire   [21:0] trunc_ln53_10_fu_159_p1;
wire   [9:0] lshr_ln53_7_fu_163_p4;
wire   [9:0] trunc_ln57_10_fu_191_p1;
wire   [21:0] lshr_ln57_7_fu_181_p4;
wire   [31:0] or_ln57_7_fu_195_p3;
wire   [31:0] or_ln53_7_fu_173_p3;
wire   [31:0] select_ln51_7_fu_203_p3;
wire   [31:0] select_ln51_fu_151_p3;
wire   [25:0] trunc_ln53_fu_218_p1;
wire   [5:0] lshr_ln53_8_fu_222_p4;
wire   [5:0] trunc_ln57_fu_250_p1;
wire   [25:0] lshr_ln57_8_fu_240_p4;
wire   [31:0] or_ln57_8_fu_254_p3;
wire   [31:0] or_ln53_8_fu_232_p3;
wire   [20:0] trunc_ln53_7_fu_270_p1;
wire   [10:0] lshr_ln53_9_fu_274_p4;
wire   [10:0] trunc_ln57_7_fu_302_p1;
wire   [20:0] lshr_ln57_9_fu_292_p4;
wire   [31:0] or_ln57_9_fu_306_p3;
wire   [31:0] or_ln53_9_fu_284_p3;
wire   [6:0] trunc_ln53_8_fu_322_p1;
wire   [24:0] lshr_ln53_s_fu_326_p4;
wire   [24:0] trunc_ln57_8_fu_354_p1;
wire   [6:0] lshr_ln57_s_fu_344_p4;
wire   [31:0] or_ln57_s_fu_358_p3;
wire   [31:0] or_ln53_s_fu_336_p3;
wire   [31:0] select_ln51_8_fu_262_p3;
wire   [31:0] select_ln51_10_fu_366_p3;
wire   [31:0] xor_ln186_fu_374_p2;
wire   [31:0] select_ln51_9_fu_314_p3;

always @ (*) begin
    if ((tmp_fu_91_p3 == 1'd1)) begin
        ap_phi_mux_p_0_phi_fu_81_p4 = xor_ln186_1_fu_380_p2;
    end else if ((tmp_fu_91_p3 == 1'd0)) begin
        ap_phi_mux_p_0_phi_fu_81_p4 = xor_ln181_fu_211_p2;
    end else begin
        ap_phi_mux_p_0_phi_fu_81_p4 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign ap_return = ap_phi_mux_p_0_phi_fu_81_p4;

assign lshr_ln53_7_fu_163_p4 = {{x[31:22]}};

assign lshr_ln53_8_fu_222_p4 = {{x[31:26]}};

assign lshr_ln53_9_fu_274_p4 = {{x[31:21]}};

assign lshr_ln53_s_fu_326_p4 = {{x[31:7]}};

assign lshr_ln57_7_fu_181_p4 = {{x[31:10]}};

assign lshr_ln57_8_fu_240_p4 = {{x[31:6]}};

assign lshr_ln57_9_fu_292_p4 = {{x[31:11]}};

assign lshr_ln57_s_fu_344_p4 = {{x[31:25]}};

assign lshr_ln9_fu_129_p4 = {{x[31:4]}};

assign lshr_ln_fu_111_p4 = {{x[31:28]}};

assign or_ln3_fu_143_p3 = {{trunc_ln57_9_fu_139_p1}, {lshr_ln9_fu_129_p4}};

assign or_ln53_7_fu_173_p3 = {{trunc_ln53_10_fu_159_p1}, {lshr_ln53_7_fu_163_p4}};

assign or_ln53_8_fu_232_p3 = {{trunc_ln53_fu_218_p1}, {lshr_ln53_8_fu_222_p4}};

assign or_ln53_9_fu_284_p3 = {{trunc_ln53_7_fu_270_p1}, {lshr_ln53_9_fu_274_p4}};

assign or_ln53_s_fu_336_p3 = {{trunc_ln53_8_fu_322_p1}, {lshr_ln53_s_fu_326_p4}};

assign or_ln57_7_fu_195_p3 = {{trunc_ln57_10_fu_191_p1}, {lshr_ln57_7_fu_181_p4}};

assign or_ln57_8_fu_254_p3 = {{trunc_ln57_fu_250_p1}, {lshr_ln57_8_fu_240_p4}};

assign or_ln57_9_fu_306_p3 = {{trunc_ln57_7_fu_302_p1}, {lshr_ln57_9_fu_292_p4}};

assign or_ln57_s_fu_358_p3 = {{trunc_ln57_8_fu_354_p1}, {lshr_ln57_s_fu_344_p4}};

assign or_ln_fu_121_p3 = {{trunc_ln53_9_fu_107_p1}, {lshr_ln_fu_111_p4}};

assign select_ln51_10_fu_366_p3 = ((tmp_4_fu_99_p3[0:0] === 1'b1) ? or_ln57_s_fu_358_p3 : or_ln53_s_fu_336_p3);

assign select_ln51_7_fu_203_p3 = ((tmp_4_fu_99_p3[0:0] === 1'b1) ? or_ln57_7_fu_195_p3 : or_ln53_7_fu_173_p3);

assign select_ln51_8_fu_262_p3 = ((tmp_4_fu_99_p3[0:0] === 1'b1) ? or_ln57_8_fu_254_p3 : or_ln53_8_fu_232_p3);

assign select_ln51_9_fu_314_p3 = ((tmp_4_fu_99_p3[0:0] === 1'b1) ? or_ln57_9_fu_306_p3 : or_ln53_9_fu_284_p3);

assign select_ln51_fu_151_p3 = ((tmp_4_fu_99_p3[0:0] === 1'b1) ? or_ln3_fu_143_p3 : or_ln_fu_121_p3);

assign tmp_4_fu_99_p3 = rtl_key_r[32'd6];

assign tmp_fu_91_p3 = rtl_key_r[32'd2];

assign trunc_ln53_10_fu_159_p1 = x[21:0];

assign trunc_ln53_7_fu_270_p1 = x[20:0];

assign trunc_ln53_8_fu_322_p1 = x[6:0];

assign trunc_ln53_9_fu_107_p1 = x[27:0];

assign trunc_ln53_fu_218_p1 = x[25:0];

assign trunc_ln57_10_fu_191_p1 = x[9:0];

assign trunc_ln57_7_fu_302_p1 = x[10:0];

assign trunc_ln57_8_fu_354_p1 = x[24:0];

assign trunc_ln57_9_fu_139_p1 = x[3:0];

assign trunc_ln57_fu_250_p1 = x[5:0];

assign xor_ln181_fu_211_p2 = (select_ln51_fu_151_p3 ^ select_ln51_7_fu_203_p3);

assign xor_ln186_1_fu_380_p2 = (xor_ln186_fu_374_p2 ^ select_ln51_9_fu_314_p3);

assign xor_ln186_fu_374_p2 = (select_ln51_8_fu_262_p3 ^ select_ln51_10_fu_366_p3);

endmodule //EP1
