// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module SIG0 (
        ap_ready,
        x,
        rtl_key_r,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] rtl_key_r;
output  [31:0] ap_return;

wire   [31:0] xor_ln202_1_fu_223_p2;
reg   [31:0] ap_phi_mux_p_0_phi_fu_73_p4;
wire   [0:0] tmp_fu_83_p3;
wire   [31:0] xor_ln207_fu_334_p2;
wire   [24:0] trunc_ln53_5_fu_99_p1;
wire   [6:0] lshr_ln_fu_103_p4;
wire   [6:0] trunc_ln57_5_fu_131_p1;
wire   [24:0] lshr_ln7_fu_121_p4;
wire   [0:0] tmp_3_fu_91_p3;
wire   [31:0] or_ln2_fu_135_p3;
wire   [31:0] or_ln_fu_113_p3;
wire   [13:0] trunc_ln53_6_fu_151_p1;
wire   [17:0] lshr_ln53_4_fu_155_p4;
wire   [17:0] trunc_ln57_6_fu_183_p1;
wire   [13:0] lshr_ln57_4_fu_173_p4;
wire   [31:0] or_ln57_4_fu_187_p3;
wire   [31:0] or_ln53_4_fu_165_p3;
wire   [28:0] lshr_ln8_fu_203_p4;
wire   [31:0] zext_ln202_fu_213_p1;
wire   [31:0] select_ln51_4_fu_195_p3;
wire   [31:0] xor_ln202_fu_217_p2;
wire   [31:0] select_ln51_fu_143_p3;
wire   [25:0] trunc_ln53_fu_230_p1;
wire   [5:0] lshr_ln53_5_fu_234_p4;
wire   [5:0] trunc_ln57_fu_262_p1;
wire   [25:0] lshr_ln57_5_fu_252_p4;
wire   [31:0] or_ln57_5_fu_266_p3;
wire   [31:0] or_ln53_5_fu_244_p3;
wire   [23:0] trunc_ln53_4_fu_282_p1;
wire   [7:0] lshr_ln53_6_fu_286_p4;
wire   [7:0] trunc_ln57_4_fu_314_p1;
wire   [23:0] lshr_ln57_6_fu_304_p4;
wire   [31:0] or_ln57_6_fu_318_p3;
wire   [31:0] or_ln53_6_fu_296_p3;
wire   [31:0] select_ln51_6_fu_326_p3;
wire   [31:0] select_ln51_5_fu_274_p3;

always @ (*) begin
    if ((tmp_fu_83_p3 == 1'd1)) begin
        ap_phi_mux_p_0_phi_fu_73_p4 = xor_ln207_fu_334_p2;
    end else if ((tmp_fu_83_p3 == 1'd0)) begin
        ap_phi_mux_p_0_phi_fu_73_p4 = xor_ln202_1_fu_223_p2;
    end else begin
        ap_phi_mux_p_0_phi_fu_73_p4 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign ap_return = ap_phi_mux_p_0_phi_fu_73_p4;

assign lshr_ln53_4_fu_155_p4 = {{x[31:14]}};

assign lshr_ln53_5_fu_234_p4 = {{x[31:26]}};

assign lshr_ln53_6_fu_286_p4 = {{x[31:24]}};

assign lshr_ln57_4_fu_173_p4 = {{x[31:18]}};

assign lshr_ln57_5_fu_252_p4 = {{x[31:6]}};

assign lshr_ln57_6_fu_304_p4 = {{x[31:8]}};

assign lshr_ln7_fu_121_p4 = {{x[31:7]}};

assign lshr_ln8_fu_203_p4 = {{x[31:3]}};

assign lshr_ln_fu_103_p4 = {{x[31:25]}};

assign or_ln2_fu_135_p3 = {{trunc_ln57_5_fu_131_p1}, {lshr_ln7_fu_121_p4}};

assign or_ln53_4_fu_165_p3 = {{trunc_ln53_6_fu_151_p1}, {lshr_ln53_4_fu_155_p4}};

assign or_ln53_5_fu_244_p3 = {{trunc_ln53_fu_230_p1}, {lshr_ln53_5_fu_234_p4}};

assign or_ln53_6_fu_296_p3 = {{trunc_ln53_4_fu_282_p1}, {lshr_ln53_6_fu_286_p4}};

assign or_ln57_4_fu_187_p3 = {{trunc_ln57_6_fu_183_p1}, {lshr_ln57_4_fu_173_p4}};

assign or_ln57_5_fu_266_p3 = {{trunc_ln57_fu_262_p1}, {lshr_ln57_5_fu_252_p4}};

assign or_ln57_6_fu_318_p3 = {{trunc_ln57_4_fu_314_p1}, {lshr_ln57_6_fu_304_p4}};

assign or_ln_fu_113_p3 = {{trunc_ln53_5_fu_99_p1}, {lshr_ln_fu_103_p4}};

assign select_ln51_4_fu_195_p3 = ((tmp_3_fu_91_p3[0:0] === 1'b1) ? or_ln57_4_fu_187_p3 : or_ln53_4_fu_165_p3);

assign select_ln51_5_fu_274_p3 = ((tmp_3_fu_91_p3[0:0] === 1'b1) ? or_ln57_5_fu_266_p3 : or_ln53_5_fu_244_p3);

assign select_ln51_6_fu_326_p3 = ((tmp_3_fu_91_p3[0:0] === 1'b1) ? or_ln57_6_fu_318_p3 : or_ln53_6_fu_296_p3);

assign select_ln51_fu_143_p3 = ((tmp_3_fu_91_p3[0:0] === 1'b1) ? or_ln2_fu_135_p3 : or_ln_fu_113_p3);

assign tmp_3_fu_91_p3 = rtl_key_r[32'd6];

assign tmp_fu_83_p3 = rtl_key_r[32'd1];

assign trunc_ln53_4_fu_282_p1 = x[23:0];

assign trunc_ln53_5_fu_99_p1 = x[24:0];

assign trunc_ln53_6_fu_151_p1 = x[13:0];

assign trunc_ln53_fu_230_p1 = x[25:0];

assign trunc_ln57_4_fu_314_p1 = x[7:0];

assign trunc_ln57_5_fu_131_p1 = x[6:0];

assign trunc_ln57_6_fu_183_p1 = x[17:0];

assign trunc_ln57_fu_262_p1 = x[5:0];

assign xor_ln202_1_fu_223_p2 = (xor_ln202_fu_217_p2 ^ select_ln51_fu_143_p3);

assign xor_ln202_fu_217_p2 = (zext_ln202_fu_213_p1 ^ select_ln51_4_fu_195_p3);

assign xor_ln207_fu_334_p2 = (select_ln51_6_fu_326_p3 ^ select_ln51_5_fu_274_p3);

assign zext_ln202_fu_213_p1 = lshr_ln8_fu_203_p4;

endmodule //SIG0
