// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CH.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CH::ap_const_logic_1 = sc_dt::Log_1;
const bool CH::ap_const_boolean_1 = true;
const sc_lv<32> CH::ap_const_lv32_5 = "101";
const sc_lv<32> CH::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_logic CH::ap_const_logic_0 = sc_dt::Log_0;

CH::CH(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_and_ln97_1_fu_70_p2);
    sensitive << ( z );
    sensitive << ( xor_ln93_fu_46_p2 );

    SC_METHOD(thread_and_ln97_fu_64_p2);
    sensitive << ( x );
    sensitive << ( y );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_fu_38_p3 );
    sensitive << ( xor_ln97_fu_76_p2 );
    sensitive << ( or_ln93_1_fu_58_p2 );

    SC_METHOD(thread_or_ln93_1_fu_58_p2);
    sensitive << ( y );
    sensitive << ( or_ln93_fu_52_p2 );

    SC_METHOD(thread_or_ln93_fu_52_p2);
    sensitive << ( z );
    sensitive << ( xor_ln93_fu_46_p2 );

    SC_METHOD(thread_tmp_fu_38_p3);
    sensitive << ( rtl_key_r );

    SC_METHOD(thread_xor_ln93_fu_46_p2);
    sensitive << ( x );

    SC_METHOD(thread_xor_ln97_fu_76_p2);
    sensitive << ( and_ln97_1_fu_70_p2 );
    sensitive << ( and_ln97_fu_64_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CH_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, y, "(port)y");
    sc_trace(mVcdFile, z, "(port)z");
    sc_trace(mVcdFile, rtl_key_r, "(port)rtl_key_r");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, xor_ln93_fu_46_p2, "xor_ln93_fu_46_p2");
    sc_trace(mVcdFile, or_ln93_fu_52_p2, "or_ln93_fu_52_p2");
    sc_trace(mVcdFile, and_ln97_1_fu_70_p2, "and_ln97_1_fu_70_p2");
    sc_trace(mVcdFile, and_ln97_fu_64_p2, "and_ln97_fu_64_p2");
    sc_trace(mVcdFile, tmp_fu_38_p3, "tmp_fu_38_p3");
    sc_trace(mVcdFile, xor_ln97_fu_76_p2, "xor_ln97_fu_76_p2");
    sc_trace(mVcdFile, or_ln93_1_fu_58_p2, "or_ln93_1_fu_58_p2");
#endif

    }
}

CH::~CH() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void CH::thread_and_ln97_1_fu_70_p2() {
    and_ln97_1_fu_70_p2 = (z.read() & xor_ln93_fu_46_p2.read());
}

void CH::thread_and_ln97_fu_64_p2() {
    and_ln97_fu_64_p2 = (y.read() & x.read());
}

void CH::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void CH::thread_ap_return() {
    ap_return = (!tmp_fu_38_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_fu_38_p3.read()[0].to_bool())? xor_ln97_fu_76_p2.read(): or_ln93_1_fu_58_p2.read());
}

void CH::thread_or_ln93_1_fu_58_p2() {
    or_ln93_1_fu_58_p2 = (or_ln93_fu_52_p2.read() | y.read());
}

void CH::thread_or_ln93_fu_52_p2() {
    or_ln93_fu_52_p2 = (z.read() | xor_ln93_fu_46_p2.read());
}

void CH::thread_tmp_fu_38_p3() {
    tmp_fu_38_p3 = rtl_key_r.read().range(5, 5);
}

void CH::thread_xor_ln93_fu_46_p2() {
    xor_ln93_fu_46_p2 = (x.read() ^ ap_const_lv32_FFFFFFFF);
}

void CH::thread_xor_ln97_fu_76_p2() {
    xor_ln97_fu_76_p2 = (and_ln97_1_fu_70_p2.read() ^ and_ln97_fu_64_p2.read());
}

}

